version: '3.4'

services:
  app:
    build:
      context: ../app
      dockerfile: ../docker/app/Dockerfile
    container_name: app
    tty: true
    stdin_open: true
    env_file:
      - app.env
    volumes:
      - ../app:/app
